/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dtconsole;


import javax.swing.JOptionPane;


/**
 * MapDialog create the dialog which consist a map picture
 * show information if mouse is hover over site area
 * @author ChinWeiQing
 * @version 2.0
 */
public class MapDialog extends javax.swing.JDialog {
    DengueFighter df;

    
    /**
     * Creates new Map Dialog
     * @param parent DTGUI
     * @param modal boolean
     */
    public MapDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
  
        df = ((DTGUI)parent).getDengueFighter();
        initComponents();
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane2 = new javax.swing.JLayeredPane();
        MapPanel = new MapPanel(df.getDengueFighterSites());
        jLabel1 = new javax.swing.JLabel();
        InstructionLabel = new javax.swing.JLabel();
        bMapLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Map");
        setResizable(false);

        jLayeredPane2.setMaximumSize(new java.awt.Dimension(693, 579));
        jLayeredPane2.setMinimumSize(new java.awt.Dimension(693, 579));

        MapPanel.setMaximumSize(new java.awt.Dimension(693, 579));
        MapPanel.setMinimumSize(new java.awt.Dimension(693, 579));
        MapPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                MapPanelMouseMoved(evt);
            }
        });
        MapPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Charlemagne Std", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("picture belong to their respective owner");
        MapPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        InstructionLabel.setFont(new java.awt.Font("Charlemagne Std", 1, 24)); // NOI18N
        InstructionLabel.setForeground(new java.awt.Color(255, 51, 0));
        InstructionLabel.setText("Hover Over to View Detail");
        InstructionLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        MapPanel.add(InstructionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 540, -1, -1));

        bMapLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dtconsole/Tayninhmap.jpg"))); // NOI18N
        bMapLabel.setMaximumSize(new java.awt.Dimension(693, 579));
        bMapLabel.setMinimumSize(new java.awt.Dimension(693, 579));
        bMapLabel.setName(""); // NOI18N
        bMapLabel.setPreferredSize(new java.awt.Dimension(693, 579));
        MapPanel.add(bMapLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MapPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MapPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jLayeredPane2.setLayer(MapPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * listen to the mouse (x,y)
     * show site information when mouse in within site area
     * @param evt 
     */
    private void MapPanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MapPanelMouseMoved
        // TODO add your handling code here:double X = evt.getX();
        double X = evt.getX();
        double Y = evt.getY();
        MapPanel a= ((MapPanel)MapPanel);
        
        try{
        String siteID = a.getSiteNo(X,Y);
        Site s =df.findSite(siteID);
        String info = ("SiteID:"+s.getSiteID()+"\nCleanliness:"+s.getCleanliness()+"\nPopulation:"+s.getPopulation()+"\nInfected:"+s.getNumInfected());
        if(siteID != null)
            JOptionPane.showMessageDialog(this,info);
        }
        catch (NullPointerException e)
        {  
        }
    }//GEN-LAST:event_MapPanelMouseMoved

   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        
        
        
        
        
        
        
        
        
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MapDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MapDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MapDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MapDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MapDialog dialog = new MapDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel InstructionLabel;
    private javax.swing.JPanel MapPanel;
    private javax.swing.JLabel bMapLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane2;
    // End of variables declaration//GEN-END:variables
}
